"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-02 12:52:01.522599
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("station", sa.String(length=100), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("prefix", name=op.f("uq_api_keys_prefix")),
    )
    op.create_table(
        "images",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=300), nullable=False),
        sa.Column("content_type", sa.String(length=50), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("bytes", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_images")),
        sa.UniqueConstraint("sha256", name=op.f("uq_images_sha256")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("api_key_id", sa.Uuid(), nullable=False),
        sa.Column("product_code", sa.String(length=100), nullable=False),
        sa.Column("product_name", sa.String(length=200), nullable=True),
        sa.Column("operator", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("client_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["api_key_id"], ["api_keys.id"], name=op.f("fk_sessions_api_key_id_api_keys")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(op.f("ix_sessions_product_code"), "sessions", ["product_code"], unique=False)
    op.create_table(
        "boards",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("board_key", sa.String(length=100), nullable=False),
        sa.Column("barcode", sa.String(length=100), nullable=True),
        sa.Column("serial", sa.String(length=100), nullable=True),
        sa.Column("verdict", sa.String(length=8), nullable=True),
        sa.Column("verdict_operator", sa.String(length=100), nullable=True),
        sa.Column("verdict_comment", sa.Text(), nullable=True),
        sa.Column("verdict_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], name=op.f("fk_boards_session_id_sessions")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_boards")),
        sa.UniqueConstraint("session_id", "board_key", name="uq_boards_session_board_key"),
    )
    op.create_index(op.f("ix_boards_barcode"), "boards", ["barcode"], unique=False)
    op.create_table(
        "reference_images",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("side", sa.SmallInteger(), nullable=False),
        sa.Column("image_id", sa.Uuid(), nullable=False),
        sa.Column("mask_storage_key", sa.String(length=300), nullable=False),
        sa.Column("mask_strategy", sa.String(length=32), nullable=False),
        sa.Column("mask_polygon", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("mask_coverage", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("source_inspection_id", sa.Uuid(), nullable=True),
        sa.Column("board_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["board_id"], ["boards.id"], name=op.f("fk_reference_images_board_id_boards")
        ),
        sa.ForeignKeyConstraint(
            ["image_id"], ["images.id"], name=op.f("fk_reference_images_image_id_images")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_reference_images_session_id_sessions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_images")),
    )
    op.create_index(op.f("ix_reference_images_session_id"), "reference_images", ["session_id"], unique=False)
    op.create_index(
        "uq_reference_images_active_side",
        "reference_images",
        ["session_id", "side"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "inspections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("board_id", sa.Uuid(), nullable=False),
        sa.Column("side", sa.SmallInteger(), nullable=False),
        sa.Column("reference_id", sa.Uuid(), nullable=False),
        sa.Column("image_id", sa.Uuid(), nullable=False),
        sa.Column("api_key_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("stage", sa.String(length=16), nullable=True),
        sa.Column("superseded", sa.Boolean(), nullable=False),
        sa.Column("rejection_code", sa.String(length=32), nullable=True),
        sa.Column("rejection", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("quality", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("transform", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("aligned_storage_key", sa.String(length=300), nullable=True),
        sa.Column("heatmap_storage_key", sa.String(length=300), nullable=True),
        sa.Column("engine_name", sa.String(length=50), nullable=False),
        sa.Column("engine_version", sa.String(length=20), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("timings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["api_key_id"], ["api_keys.id"], name=op.f("fk_inspections_api_key_id_api_keys")
        ),
        sa.ForeignKeyConstraint(["board_id"], ["boards.id"], name=op.f("fk_inspections_board_id_boards")),
        sa.ForeignKeyConstraint(["image_id"], ["images.id"], name=op.f("fk_inspections_image_id_images")),
        sa.ForeignKeyConstraint(
            ["reference_id"],
            ["reference_images.id"],
            name=op.f("fk_inspections_reference_id_reference_images"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_inspections_session_id_sessions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inspections")),
        sa.UniqueConstraint("api_key_id", "idempotency_key", name="uq_inspections_api_key_idempotency_key"),
    )
    op.create_index("ix_inspections_board_side", "inspections", ["board_id", "side"], unique=False)
    op.create_index(op.f("ix_inspections_rejection_code"), "inspections", ["rejection_code"], unique=False)
    op.create_index(op.f("ix_inspections_session_id"), "inspections", ["session_id"], unique=False)
    op.create_index(op.f("ix_inspections_status"), "inspections", ["status"], unique=False)
    # circular reference_images <-> inspections: added once both tables exist
    op.create_foreign_key(
        "fk_reference_images_source_inspection_id_inspections",
        "reference_images",
        "inspections",
        ["source_inspection_id"],
        ["id"],
    )
    op.create_table(
        "defects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("inspection_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("area", sa.Integer(), nullable=True),
        sa.Column("test_x", sa.Integer(), nullable=False),
        sa.Column("test_y", sa.Integer(), nullable=False),
        sa.Column("test_w", sa.Integer(), nullable=False),
        sa.Column("test_h", sa.Integer(), nullable=False),
        sa.Column("ref_x", sa.Integer(), nullable=False),
        sa.Column("ref_y", sa.Integer(), nullable=False),
        sa.Column("ref_w", sa.Integer(), nullable=False),
        sa.Column("ref_h", sa.Integer(), nullable=False),
        sa.Column("verdict", sa.String(length=10), nullable=False),
        sa.Column("defect_type", sa.String(length=32), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("verdict_operator", sa.String(length=100), nullable=True),
        sa.Column("verdict_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["inspection_id"], ["inspections.id"], name=op.f("fk_defects_inspection_id_inspections")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_defects")),
    )
    op.create_index(op.f("ix_defects_inspection_id"), "defects", ["inspection_id"], unique=False)
    op.create_index(op.f("ix_defects_verdict"), "defects", ["verdict"], unique=False)
    op.create_table(
        "defect_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("defect_id", sa.Uuid(), nullable=False),
        sa.Column("event", sa.String(length=32), nullable=False),
        sa.Column("old", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("operator", sa.String(length=100), nullable=True),
        sa.Column("api_key_id", sa.Uuid(), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["api_key_id"], ["api_keys.id"], name=op.f("fk_defect_events_api_key_id_api_keys")
        ),
        sa.ForeignKeyConstraint(
            ["defect_id"], ["defects.id"], name=op.f("fk_defect_events_defect_id_defects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_defect_events")),
    )
    op.create_index(op.f("ix_defect_events_defect_id"), "defect_events", ["defect_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_defect_events_defect_id"), table_name="defect_events")
    op.drop_table("defect_events")
    op.drop_index(op.f("ix_defects_verdict"), table_name="defects")
    op.drop_index(op.f("ix_defects_inspection_id"), table_name="defects")
    op.drop_table("defects")
    op.drop_index(op.f("ix_inspections_status"), table_name="inspections")
    op.drop_index(op.f("ix_inspections_session_id"), table_name="inspections")
    op.drop_index(op.f("ix_inspections_rejection_code"), table_name="inspections")
    op.drop_index("ix_inspections_board_side", table_name="inspections")
    op.drop_constraint(
        "fk_reference_images_source_inspection_id_inspections", "reference_images", type_="foreignkey"
    )
    op.drop_table("inspections")
    op.drop_index(
        "uq_reference_images_active_side",
        table_name="reference_images",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index(op.f("ix_reference_images_session_id"), table_name="reference_images")
    op.drop_table("reference_images")
    op.drop_index(op.f("ix_boards_barcode"), table_name="boards")
    op.drop_table("boards")
    op.drop_index(op.f("ix_sessions_product_code"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("images")
    op.drop_table("api_keys")
    # ### end Alembic commands ###
